services:
  incidenthistory:
    container_name: incident-history
    build:
      context: .
      dockerfile: IncidentHistoryService/Dockerfile
    ports:
      - 8100:80

  preventive-works:
    container_name: preventive-works
    build: ./preventive-works
    ports:
      - 8101:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    container_name: mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: preventive_works
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo-dev
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo