services:
  incidenthistory:
    container_name: incident-history
    build:
      context: .
      dockerfile: IncidentHistoryService/Dockerfile
    ports:
      - 8100:80

  preventive-works:
    container_name: preventive-works
    build: ./preventive-works
    ports:
      - 8101:8080