definitions:
  models.Event:
    properties:
      create_at:
        type: string
      deadline:
        type: string
      description:
        type: string
      status:
        type: string
    type: object
  models.PreventiveWork:
    properties:
      create_at:
        type: string
      deadline:
        type: string
      description:
        type: string
      events:
        items:
          $ref: '#/definitions/models.Event'
        type: array
      id:
        type: string
      id_service:
        type: string
      title:
        type: string
    type: object
host: localhost:8101
info:
  contact: {}
  description: API для отслеживания профилактических работ
  title: preventive-works
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PreventiveWork'
            type: array
        "404":
          description: Not Found
          schema:
            type: integer
      summary: отображение всех профилактических работ
      tags:
      - PreventiveWorks
  /{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: PreventiveWork id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PreventiveWork'
        "404":
          description: Not Found
          schema:
            type: integer
      summary: отображение профилактической работы по id
      tags:
      - PreventiveWork
  /{id}/new_event:
    put:
      parameters:
      - description: id профилактической работы
        in: path
        name: id
        required: true
        type: string
      - description: Статус события
        in: formData
        name: status
        required: true
        type: string
      - description: Дата создания события
        in: formData
        name: create_at
        required: true
        type: string
      - description: Дата окончания события
        in: formData
        name: deadline
        required: true
        type: string
      - description: Описание события
        in: formData
        name: description
        required: true
        type: string
      responses:
        "200":
          description: ""
        "404":
          description: Not Found
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      summary: добавление новой профилактической работы
      tags:
      - NewEvent
  /new_work:
    post:
      parameters:
      - description: Имя сервиса
        in: formData
        name: name_service
        required: true
        type: string
      - description: Дата создания профил. работы
        in: formData
        name: create_at
        required: true
        type: string
      - description: Дата окончания профил. работы
        in: formData
        name: deadline
        required: true
        type: string
      - description: Название профил. работы
        in: formData
        name: title
        required: true
        type: string
      - description: Описание профил. работы
        in: formData
        name: description
        required: true
        type: string
      responses:
        "200":
          description: ""
        "404":
          description: Not Found
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            type: integer
      summary: добавление новой профилактической работы
      tags:
      - NewPreventiveWork
swagger: "2.0"
